### ISSUE TITLE
Enter with no markup causes AttributeError

### ISSUE THREAD

**Issue by hakase** [hakase/japanese#2]
```
sentence: 毎日、公園に行きますよ。
Traceback (most recent call last):
  File "tetsudai.py", line 111, in <module>
    main()
  File "tetsudai.py", line 79, in main
    word = soup.find('span', attrs={'style': 'color: #3F7EBE;'}).string
AttributeError: 'NoneType' object has no attribute 'string'
```

**Comment by hakase** [comment]
fixed in 89965cd43a119a962d8d3b58c763ab7e7c5a7604
